name: rllab3
channels:
    - conda-forge
    - toli
dependencies:
    - python==3.6
    - numpy
    - path
    - scipy
    - mako
    - joblib
    - tensorflow==1.14
    - pyprind
    - cached-property
    - matplotlib
    - cython<3
    - pip:
        - Pillow
        - git+https://github.com/Theano/Theano.git@adfe319ce6b781083d8dc3200fb4481b00853791#egg=Theano
        - git+https://github.com/neocxi/Lasagne.git@484866cf8b38d878e92d521be445968531646bb8#egg=Lasagne
        - mujoco_py==0.5.7
        - pyparsing==2.4.7
        - opencv-python-headless
